### PR TITLE
[update] Ruboty can catch all messages

### PR DESCRIPTION
**Pull request by nikukyugamer**
Hi

previously, Ruboty can catch only one message as below
```ruby
            robot.receive(
              body: message[0]['body'],
              from_name: message[0]['account']['name']
            )
```

so, I modified to catch all messages. `robot.receive` not only message[0] but also message\[0..X\](all).

### CODE REVIEW

**Comment by mhag** [comment]
@corselia 

Thanks for your p-r.

I merged #2 , so this p-r has conflict 😢 
Would you resolve it?

**Comment by nikukyugamer** [comment]
@mhag 

sorry, sorry and sorry...
I miss your comment until now, sorry.
I investigate it as soon as possible. 

SORRY

**Comment by mhag** [comment]
@corselia 

Thanks for your reply.

Please let me know if you have any problems.

:innocent:

**Comment by mhag** [comment]
I merged #4.

So I close this p-r.

**Pull request closed without merging**
